from enum import Enum


class UserRole(str, Enum):
    SUPERADMIN = "SUPERADMIN"
    ADMIN = "ADMIN"
    TEACHER = "TEACHER"
    STUDENT = "STUDENT"


class SessionRevokedReason(str, Enum):
    LOGOUT = "LOGOUT"
    LOGOUT_ALL = "LOGOUT_ALL"
    IDLE_TIMEOUT = "IDLE_TIMEOUT"
    REFRESH_TOKEN_REUSE_DETECTED = "REFRESH_TOKEN_REUSE_DETECTED"
    ADMIN_FORCE_LOGOUT = "ADMIN_FORCE_LOGOUT"
    USER_FORCE_LOGOUT = "USER_FORCE_LOGOUT"
