"""initial tables

Revision ID: eef34b1362c2
Revises:
Create Date: 2026-08-05 09:21:43.696934

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "eef34b1362c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_text", sa.Text(), nullable=False),
        sa.Column("answer_key_raw", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=20), nullable=False),
        sa.Column("required_count", sa.SmallInteger(), nullable=True),
        sa.Column("bloom_level", sa.String(length=10), nullable=True),
        sa.Column("complexity_score", sa.SmallInteger(), nullable=True),
        sa.Column("education_level", sa.String(length=10), nullable=False),
        sa.Column("education_class", sa.String(length=50), nullable=False),
        sa.Column("generation_status", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assessment_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("student_answer", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("concept_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("semantic_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("logic_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("reasoning_score", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("ai_confidence", sa.Numeric(precision=4, scale=3), nullable=True),
        sa.Column("ai_explainability", sa.Text(), nullable=True),
        sa.Column("ai_feedback", sa.Text(), nullable=True),
        sa.Column("matched_items", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("eval_model_used", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concept_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("relation_text", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "concepts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("concept_text", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rubric_criteria",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("ku_id", sa.String(length=50), nullable=False),
        sa.Column("criterion_text", sa.Text(), nullable=False),
        sa.Column("weight", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("bloom_level", sa.String(length=10), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("question_id", "ku_id"),
    )
    op.create_table(
        "rubric_scores",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("assessment_session_id", sa.UUID(), nullable=False),
        sa.Column("rubric_criterion_id", sa.UUID(), nullable=False),
        sa.Column("achieved", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["assessment_session_id"], ["assessment_sessions.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["rubric_criterion_id"], ["rubric_criteria.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("assessment_session_id", "rubric_criterion_id"),
    )
    op.create_table(
        "token_usage_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=True),
        sa.Column("assessment_session_id", sa.UUID(), nullable=True),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["assessment_session_id"], ["assessment_sessions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token_usage_logs")
    op.drop_table("rubric_scores")
    op.drop_table("rubric_criteria")
    op.drop_table("concepts")
    op.drop_table("concept_relations")
    op.drop_table("assessment_sessions")
    op.drop_table("questions")
    # ### end Alembic commands ###
